$CATEGORIAS = [
	{search: 'arboles' , name: 'Arboles', img: '/imgcategorias/9.jpg'},
	{search: 'arboles frutales' , name: 'Arboles Frutales', img: '/imgcategorias/25.jpg'},
	{search: 'arborescentes' , name: 'Plantas Arborescentes',  img: '/imgcategorias/81.png'},
	{search: 'orquideas', name: 'Orquídea',  img: '/imgcategorias/128.jpg'},
	{search: 'semillas', name: 'Semillas', img: '/imgcategorias/semillas.jpg'},
	{search: 'palmas' , name: 'Palmas', img: '/imgcategorias/31.jpg'},
	{search: 'arbustos' , name: 'Arbustos',  img: '/imgcategorias/11.jpg'},
	{search: 'enredaderas trepadoras' , name: 'Enredaderas o Trepadoras',  img:  '/imgcategorias/67.jpg'},
	{search: 'enredaderas sol' , name: 'Enredaderas Para el Sol',  img:  '/imgcategorias/69.jpg'},
	{search: 'plantas de sol' , name: 'Plantas de Sol',  img: '/imgcategorias/62b.png'},
	{search: 'plantas de sol y sombra' , name: 'Plantas de Sol y Sombra',  img: '/imgcategorias/97.png'},
	{search: 'follaje y flor para sombra y media sombra' , name: 'Plantas de follaje y flor para sombra y media sombra', img: ''},
	{search: 'setos' , name: 'Plantas para setos',  img: '/imgcategorias/47.png'},
	{search: 'cubrepisos' , name: 'Plantas para cubrepisos', img: ''},
	{search: 'anuales y perenes con flores' , name: 'Plantas anuales y perenes con flores de poca duración', img: ''},
	{search: 'follaje ornamental' , name: 'Plantas con follaje ornamental', img: ''},
	{search: 'flor cortada' , name: 'Flor Cortada', img: ''},
	{search: 'macetas y decoraciones' , name: 'Macetas y Decoraciones de Jardín', img: ''},
	{search: 'herramientas', name: 'Herramientas de Jardín', img: ''},
	{search: 'tierra y abonos', name: 'Tierra, Abonos y Sustratos', img: ''},
	{search: 'muebles y mobiliario', name: 'Muebles y mobiliario de Jardín', img: ''}
]